### PR TITLE
Use Vue 3 Plugin Augmentation

### PR DESCRIPTION
**Pull request by GizmoTjaz**
The current declaration file gives me errors when building my Vue 3 project, since it's using the Vue 2 plugin augmentation.

### CODE REVIEW

**Comment by ComradeVanti** [comment]
Looks like a no-brainer to me. Why is this not merged? @kil0ba

**Comment by Grawl** [comment]
Thank you for this PR, I got the declarations and put them into my Quasar 2 / Vue 3 project. It works, no typescript errors for now.

**Comment by dclause** [comment]
This PR adds vue and vuex as dependencies to the project. That means vuex dependency is no more optional and will be added to your project even if it does not use it. I don't think that is a good thing.

**Comment by GizmoTjaz** [comment]
Apologies for the late response, but I had completely forgotten about this PR and deleted the forked repo a long time ago, so it is pretty much irrecoverable now. I decided to open a new PR, with some further improvements.

@dclause I have addressed your feedback in my new PR, please let me know if it's correct.

New PR: https://github.com/kil0ba/Vue-3-Socket.io/pull/6

**Pull request closed without merging**
